package:
  name: pymbd
  version: 0.9.0

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - {{ compiler('fortran') }}
    - cmake
    - libopenblas
    - poetry
  host:
    - python
    - pip
    - cffi
  run:
    - python
    - cffi
    - numpy
    - scipy
    - libopenblas

test:
  requires:
    - pytest
  commands:
    - pytest -vs --durations=3
  source_files:
    - tests

about:
  home: https://github.com/jhrmnn/libmbd
  license: MPL-2.0
  license_file: LICENSE
  summary: Many-body dispersion library

extra:
  recipe-maintainers:
    - jhrmnn
