name: Documentation
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo $HOME/.poetry/bin >>$GITHUB_PATH
      - name: Install dependencies
        run: pip install sphinx toml git+https://github.com/libmbd/ford@7b44574da7ec20f4ab4b1842ec7561de2a601930
      - uses: actions/checkout@v2
      - name: Libmbd documentation
        run: ford -I. docs/libmbd.md -o build
      - name: Pymbd documentation
        run: sphinx-build -W -d build/doctrees docs docs/build/pymbd
      - run: touch docs/build/.nojekyll
